profile: personal
region: us-east-1
versioning: false
default_alias: null
clean_build: true
configuration:
  name: AlexaZork
  runtime: python2.7
  role: arn:aws:iam::ACCOUNTID:role/service-role/AlexaZork2
  handler: lambda_function.lambda_handler
  description: Zork for Alexa
  timeout: 10
  memory_size: 128
